# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-TAP-HTMLMatrix
version:      0.07
version_from: lib/Test/TAP/HTMLMatrix.pm
installdirs:  site
requires:
    Petal:                         0
    Petal::Utils:                  0
    Test::More:                    0
    Test::TAP::Model:              >= 0.08
    URI::file:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
