--- #YAML:1.0
name:                Test-TAP-HTMLMatrix
version:             0.09
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Petal:                         0
    Petal::Utils:                  0
    Test::More:                    0
    Test::TAP::Model:              >= 0.08
    URI::file:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
